LL-4545 start announcements logic
LedgerHQ/ledger-live-common pull request #1057
Opened 2021-02-09 18:00 UTC by valpinkman

cc: @IAmMorrow

2021-02-12 13:07 UTC, gre commented on src/announcements/react.js
> +      }, {});
reduce to build a `{}` is imo an anti-pattern (fact we mutate the accumulator), we could just forEach and with a `const cache = {};` that we fill from inside forEach.

2021-02-12 13:07 UTC, gre commented on src/announcements/react.js
> +    }
there is almost twice the same code.

2021-02-12 13:07 UTC, gre commented on src/announcements/react.js
> +type Context = {
I think we really want to find another name. "Context" collides with react's Context naming, and here it's not even the "context" provided by your AnnouncementsContext.

I usually call this "user settings". like in CountervaluesUserSettings.

2021-02-12 13:07 UTC, gre commented on src/announcements/react.js
> +    if (publishedAt.getTime() > date.getTime()) {
you don't need to `getTime()` to compare dates

2021-02-12 13:07 UTC, gre commented on src/announcements/react.js
> +      new Date(announcement.expired_at).getTime() < date.getTime()
same

2021-02-12 13:51 UTC, LFBarreto requested changes

2021-02-12 13:51 UTC, LFBarreto commented on src/announcements/react.js
> +export const useAnnouncements = (): Context => useContext(AnnoucementsContext);
I think there's an issue on the type returned here not the correct one

2021-02-25 15:45 UTC, gre commented on package.json
> +    "@xstate/react": "^1.3.1",
will this be a problem if we depends on live-common from CLI project?

2021-02-26 07:11 UTC, gre reviewed
Not super convinced by the usage of xstate here. We managed to do more complex things that this without xstate and it's sometimes easier to read.
Personally I can't understand what's the machine is about and why it's needed.

I think if we can afford to drop it we should

2021-02-26 07:11 UTC, gre commented on src/announcements/react.js
> +  onLoad: () => Promise<{
I don't like the wording onLoad/onSave because it makes think it's just an event (like onClick) but actually it's the actual load/save

2021-02-26 07:11 UTC, gre commented on src/announcements/react.js
> +  context: AnnoucementsUserSettings,
Is it possible to also rename the prop?

2021-02-26 07:11 UTC, gre commented on src/announcements/machine.js
> +);
Maybe it's just me but the complexity brought by the xstate approach is a bit overwhelming and I'm not confident reviewing that part myself.
I'm not sure who's in the team have enough knowledge of this.

2021-02-26 08:15 UTC, gre commented
ok let's keep xstate & schedule internal prez about this.

2021-03-03 18:17 UTC, IAmMorrow commented
We are seeing the end of the tunnel on this.

2021-03-12 13:11 UTC, gre commented
I suggest to rename `providers` folder to `announcements`

2021-03-12 13:45 UTC, merged