LL-4555 LL-4222 LL-4219 - Feature/ethereum transactions updates
LedgerHQ/ledger-live-common pull request #1127
Opened 2021-03-30 14:06 UTC by machard

https://ledgerhq.atlassian.net/browse/LL-4222
https://ledgerhq.atlassian.net/browse/LL-4555
https://ledgerhq.atlassian.net/browse/LL-4219

- [x] allow send transaction with 0 amount with a special flag
- [x] sign message api update to allow desktop to pass its own sign command
- [x] wc: clean current request id when disconnected
- [x] add data field for send transaction with data
- [ ] no amount required for erc20.approve
- [ ] remap transaction to erc20.approve only if the token is in the jean list

2021-04-08 16:16 UTC, valpinkman approved these changes

2021-04-12 09:23 UTC, gre requested changes
I think we need to rediscuss the task "display approve like on device" because the code here feels very complex to even maintain

2021-04-12 09:23 UTC, gre commented on src/families/ethereum/modules/send.js
> +      if (method === "095ea7b3" && token) {
🤔 
to me this code belongs not to send but to `modules/erc20`

the code here feels quite difficult to maintain on long term and we don't want to add one entry for each future feature of ETH.

2021-04-12 09:23 UTC, gre commented on src/families/ethereum/modules/send.js
> +        if (uniq(amountHex.split("")) === ["f"]) {
i'm not confident for us to maintain this ourself. we never did the "Amount (1/2)" display on Live side at the moment and i don't think we need to start doing this unless if it's addressed very generically.

2021-04-12 19:57 UTC, gre reviewed
let's fix the lint and we should be good.

2021-04-12 19:58 UTC, gre requested changes
let's fix the lint and we should be good.

2021-04-12 20:01 UTC, gre commented
@machard how do you estimate the impact of this work on mobile?
- is it a "no changes" for LLM perspective? if i bump just live-common alone on LLM, no impact / no changes to expect?

2021-04-13 11:25 UTC, merged