LL 5253 Stellar JS: faster sync implementation
LedgerHQ/ledger-live-common pull request #1142
Opened 2021-04-19 07:59 UTC by haammar-ledger

Current implementation of account sync in Stellar JS does this:
1) Fetch all transactions of the account
2) For each transaction, fetch all operations it contains (the Stellar blockchain has both transactions, and operations contained in transactions)

This is sub-optimal and results in a significantly slower sync than with previous libcore impl, causing issues as described in https://ledgerhq.atlassian.net/browse/LL-5253.

This PR changes this mechanism to fetch directly all operations of an account in one pass.

2021-04-19 08:49 UTC, rjarasson-ledger commented
LGTM, i still would like to test it to be sure on my side, but great improvements.

2021-04-19 09:08 UTC, gre requested changes

2021-04-19 09:08 UTC, gre commented on src/families/stellar/api/horizon.js
>  import type { RawAccount, RawTransaction } from "./horizon.types";
lint

2021-04-19 15:53 UTC, rjarasson-ledger commented
We can still improve the requests by using the "join" request params to avoid N+1 requests.

2021-04-19 15:59 UTC, gre commented
BTW check the CI (windows) because it seems to fail.

```
● js bridge on account GRE's Stellar 2 › prepareTransaction › can be run in parallel and all yield same results

    Bad Request

      at new NetworkError (node_modules/stellar-sdk/src/errors.ts:25:4)
      at node_modules/stellar-sdk/lib/call_builder.js:332:41
      at step (node_modules/tslib/tslib.js:274:19)
      at Object.next (node_modules/tslib/tslib.js:205:16)
      at node_modules/tslib/tslib.js:177:69
      at Object.__awaiter (node_modules/tslib/tslib.js:156:12)
      at CallBuilder._handleNetworkError (node_modules/stellar-sdk/lib/call_builder.js:324:20)
          at runMicrotasks (<anonymous>)
```

2021-04-20 10:06 UTC, gre commented
still presence of   `Bad Request`  failures on CI

2021-04-20 10:48 UTC, haammar-ledger commented
@gre I know sorry about that, I'm on it, should be fixed soon(tm).

2021-04-20 11:21 UTC, haammar-ledger commented
@gre CI was failing because at some point the address passed here is empty: https://github.com/LedgerHQ/ledger-live-common/blob/master/src/bridge/jsHelpers.js#L129
I've sanitized the place where it was failing by checking against empty address, but I don't get why and how this can happen.

2021-04-20 13:12 UTC, rjarasson-ledger approved these changes

2021-04-20 13:16 UTC, gre approved these changes
great work guys. Go 🟦

2021-04-20 13:16 UTC, merged