added logic so announcement refresh themselves on parameter change
LedgerHQ/ledger-live-common pull request #1158
Opened 2021-04-29 14:18 UTC by IAmMorrow

This PR should ensure that announcement are correctly refreshed whenever parameters change. Please be careful that client implementation don't change the context object on every render, but rather when a param changed.

2021-04-29 14:22 UTC, gre requested changes
check linter.

2021-04-29 15:00 UTC, valpinkman requested changes
flow and eslint issues

otherwise seems good to me

2021-05-07 12:29 UTC, gre approved these changes

2021-05-07 14:45 UTC, gre commented on src/notifications/AnnouncementProvider/index.js
> +  }, [context]);
i don't really understand how this works. it is called on mount no?

2021-05-28 16:51 UTC, gre commented
@IAmMorrow no update on this so as discussed i'm closing. please create equivalent on Jira so we can plan the work.

2021-05-28 16:51 UTC, closed without merging