Elrond integration on Ledger CLI
LedgerHQ/ledger-live-common pull request #1278
Opened 2021-06-24 11:36 UTC by pislaProgramming

2021-07-28 16:33 UTC, haammar-ledger reviewed
Super clean integration! Good job :+1:

2021-07-29 07:05 UTC, AlexandruPislariu commented on src/families/elrond/js-getTransactionStatus.js
> +    errors.recipient = new ElrondSelfTransactionError(
I didn't know about this generic error, I will use it.

2021-07-29 07:08 UTC, AlexandruPislariu commented on src/families/elrond/api/apiCalls.js
> +      url: `${this.API_URL}/blocks?shard=4294967295&fields=nonce`,
No, the shard isn't arbitrary, this is the metachain shard. I will use a constant instead.

2021-07-29 07:32 UTC, AlexandruPislariu commented on src/families/elrond/api/sdk.js
> +  const { gasLimit, gasPerByte, gasPrice } = await api.getNetworkConfig();
Thanks! I didn't know this could happen a lot. I will use a cache mechanism.

2021-07-29 08:13 UTC, AlexandruPislariu commented on src/families/elrond/logic.js
> +};
I will use our sdk for address validation @elrondnetwork/erdjs, is it ok?

2021-07-29 08:16 UTC, AlexandruPislariu commented on src/families/elrond/preload.js
> +      foo = data.validators.foo || "bar";
We do not intend to implement the staking part for now, this will be a task in the future.

2021-07-29 09:28 UTC, haammar-ledger commented on src/families/elrond/preload.js
> +      foo = data.validators.foo || "bar";
Fair enough :+1:

2021-07-29 12:15 UTC, haammar-ledger requested changes
Thank you for adding tests :+1: just a few modifications needed.

You also need to add `"elrond"` in the `src/__tests__/test-helpers/setup.js` file.

To check your tests are successful please run `yarn test`.
This should also generate modifications to the `src/__tests__/__snapshots__/all.libcore.js.snap` files, please commit these modifications after the tests pass.

2021-07-29 12:15 UTC, haammar-ledger commented on src/families/elrond/test-dataset.js
> +import type { Transaction } from "./types";
Please add missing imports:
```
import { BigNumber } from "bignumber.js";
import {
  InvalidAddressBecauseDestinationIsAlsoSource,
  NotEnoughBalance,
  InvalidAddress,
} from "@ledgerhq/errors";
```

2021-07-29 12:15 UTC, haammar-ledger commented on src/families/elrond/test-dataset.js
> +};
Unused, can be removed.

2021-07-29 12:15 UTC, haammar-ledger commented on src/families/elrond/test-dataset.js
> +                numSlashingSpans: 0,
Please remove unused fields (in all 3 tests):
- era
- validators
- rewardDestination
- numSlashingSpans

2021-07-29 12:15 UTC, haammar-ledger commented on src/families/elrond/test-dataset.js
> +  implementations: ["mock", "js"],
Please use here:
```
const dataset: DatasetTest<Transaction> = {
  implementations: ["js"],
```

(with `export default dataset;`)

2021-07-30 09:21 UTC, haammar-ledger commented
Good job making the tests able to run :rocket: 
The following generic tests are currently failing for Elrond, can you please have a look?
I believe once they're fixed the PR is mergeable :+1: 

```
  ● elrond currency bridge › scanAccounts › estimateMaxSpendable is between 0 and account balance

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      267 |                   account,
      268 |                 });
    > 269 |                 expect(estimation.gte(0)).toBe(true);
          |                                           ^
      270 |                 expect(estimation.lte(account.spendableBalance)).toBe(true);
      271 |                 for (const sub of account.subAccounts || []) {
      272 |                   const estimation = await accountBridge.estimateMaxSpendable({

      at Object.<anonymous> (src/__tests__/test-helpers/bridge.js:269:43)
          at runMicrotasks (<anonymous>)

  ● js bridge on account Elrond 1 › sync › balance is sum of ops

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

    - "25477697386621408"
    + "25827697386621408"

      46 |
      47 | function expectBalanceIsOpsSum(a) {
    > 48 |   expect(a.balance).toEqual(
         |                     ^
      49 |     a.operations.reduce(
      50 |       (sum, op) => sum.plus(getOperationAmountNumber(op)),
      51 |       BigNumber(0)

      at expectBalanceIsOpsSum (src/__tests__/test-helpers/bridge.js:48:21)
      at Object.<anonymous> (src/__tests__/test-helpers/bridge.js:422:15)
          at runMicrotasks (<anonymous>)

  ● js bridge on account Elrond 1 › createTransaction › empty transaction correctly serialize

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      Object {
        "amount": "0",
        "family": "elrond",
    -   "fees": 50000,
    +   "fees": "50000",
        "mode": "send",
        "recipient": "",
        "useAllAmount": false,
      }

      522 |           makeTest("empty transaction correctly serialize", () => {
      523 |             const t = bridge.createTransaction(initialAccount);
    > 524 |             expect(fromTransactionRaw(toTransactionRaw(t))).toEqual(t);
          |                                                             ^
      525 |           });
      526 |
      527 |           makeTest(

      at Object.<anonymous> (src/__tests__/test-helpers/bridge.js:524:61)
          at runMicrotasks (<anonymous>)

  ● js bridge on account Elrond 1 › createTransaction › transaction with amount and recipient correctly serialize

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      Object {
        "amount": "1000",
        "family": "elrond",
    -   "fees": 50000,
    +   "fees": "50000",
        "mode": "send",
        "recipient": "erd1rnq7m8kdrpyfany4fweqtydsk4pgx0l6dtl6tvcad5wesagruxts62e9rk",
        "useAllAmount": false,
      }

      534 |                 recipient: account.freshAddress,
      535 |               };
    > 536 |               expect(fromTransactionRaw(toTransactionRaw(t))).toEqual(t);
          |                                                               ^
      537 |             }
      538 |           );
      539 |         });

      at Object.<anonymous> (src/__tests__/test-helpers/bridge.js:536:63)
          at runMicrotasks (<anonymous>)

  ● js bridge on account Elrond 1 › prepareTransaction › ref stability on empty transaction

    expect(received).toBe(expected) // Object.is equality

    If it should pass with deep equality, replace "toBe" with "toStrictEqual"

    Expected: {"amount": "0", "family": "elrond", "fees": "50000000000000", "mode": "send", "recipient": "", "useAllAmount": false}
    Received: serializes to the same string

      544 |             const t2 = await bridge.prepareTransaction(account, t);
      545 |             const t3 = await bridge.prepareTransaction(account, t2);
    > 546 |             expect(t2).toBe(t3);
          |                        ^
      547 |           }
      548 |
      549 |           makeTest("ref stability on empty transaction", async () => {

      at expectStability (src/__tests__/test-helpers/bridge.js:546:24)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (src/__tests__/test-helpers/bridge.js:551:13)

  ● js bridge on account Elrond 1 › prepareTransaction › ref stability on self transaction

    expect(received).toBe(expected) // Object.is equality

    If it should pass with deep equality, replace "toBe" with "toStrictEqual"

    Expected: {"amount": "1000", "family": "elrond", "fees": "50000000000000", "mode": "send", "recipient": "erd1rnq7m8kdrpyfany4fweqtydsk4pgx0l6dtl6tvcad5wesagruxts62e9rk", "useAllAmount": false}
    Received: serializes to the same string

      544 |             const t2 = await bridge.prepareTransaction(account, t);
      545 |             const t3 = await bridge.prepareTransaction(account, t2);
    > 546 |             expect(t2).toBe(t3);
          |                        ^
      547 |           }
      548 |
      549 |           makeTest("ref stability on empty transaction", async () => {

      at expectStability (src/__tests__/test-helpers/bridge.js:546:24)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (src/__tests__/test-helpers/bridge.js:556:13)

  ● js bridge on account Elrond 1 › getTransactionStatus › can be called on an empty transaction

    expect(received).toBeInstanceOf(expected)

    Expected constructor: BigNumber

    Received value has no prototype
    Received value: 50000

      594 |             expect(s.totalSpent).toBeInstanceOf(BigNumber);
      595 |             expect(s).toHaveProperty("estimatedFees");
    > 596 |             expect(s.estimatedFees).toBeInstanceOf(BigNumber);
          |                                     ^
      597 |             expect(s).toHaveProperty("amount");
      598 |             expect(s.amount).toBeInstanceOf(BigNumber);
      599 |             expect(s.amount).toEqual(BigNumber(0));

      at Object.<anonymous> (src/__tests__/test-helpers/bridge.js:596:37)
          at runMicrotasks (<anonymous>)

  ● js bridge on account Elrond 1 › getTransactionStatus › transaction Not enough balance

    expect(received).toMatchObject(expected)

    - Expected  - 3
    + Received  + 1

    - Object {
    -   "amount": [NotEnoughBalance: NotEnoughBalance],
    - }
    + Object {}

      672 |                   const { errors, warnings } = es;
      673 |                   // we match errors and warnings
    > 674 |                   errors && expect(s.errors).toMatchObject(errors);
          |                                              ^
      675 |                   warnings && expect(s.warnings).toMatchObject(warnings);
      676 |                   // now we match rest of fields but using the raw version for better readability
      677 |                   const restRaw: Object = toTransactionStatusRaw({

      at Object.<anonymous> (src/__tests__/test-helpers/bridge.js:674:46)
          at runMicrotasks (<anonymous>)

```

2021-08-02 10:13 UTC, ghost requested changes

2021-08-02 10:17 UTC, AlexandruPislariu commented on src/__tests__/test-helpers/setup.js
> +  "elrond",
Yes, right. I solved this issue.

2021-08-02 12:36 UTC, haammar-ledger approved these changes
:rocket:

2021-08-02 12:40 UTC, haammar-ledger requested changes
One last conflict to solve, probably because of incoming change in master... sorry about that. After that we're good to go.

2021-08-02 13:24 UTC, haammar-ledger approved these changes

2021-08-12 13:17 UTC, gre requested changes
CI don't pass because dups in dependencies. explanation

2021-08-12 13:17 UTC, gre commented on docs/AccountBridge.md
> +  expect(t2).toStrictEqual(t3); // t2 === t3
good catch. thanks.

2021-08-12 15:59 UTC, gre commented
can you add a validation in getTransactionStatus that will set `new RecipientRequired()` in `status.errors.recipient` when the transaction.recipient was "" ?

2021-08-12 15:59 UTC, gre commented
oh you did!

2021-08-12 16:45 UTC, gre commented
```
  ● js bridge on account Elrond 1 › getTransactionStatus › Default empty recipient have a recipientError

    expect(received).toEqual(expected) // deep equality

    Expected: [RecipientRequired: RecipientRequired]
    Received: [InvalidAddress: InvalidAddress]

      628 |               const t = { ...bridge.createTransaction(account) };
      629 |               const status = await bridge.getTransactionStatus(account, t);
    > 630 |               expect(status.errors.recipient).toEqual(new RecipientRequired());
          |                                               ^
      631 |             }
      632 |           );
      633 |           makeTest("invalid recipient have a recipientError", async () => {

```

- in specific case of recipient="" , it should return RecipientRequired in order for our UI to ask for it.

(don't worry about other error about tron and decred)

- 2 lint issues too.

2021-08-13 07:11 UTC, gre commented on src/families/elrond/js-getTransactionStatus.ts
> +  if (!t.recipient || t.recipient === "") {
`!t.recipient` covers the "" case so this code is actually redundant

2021-08-13 08:37 UTC, gre commented
We'll merge this work as it's passing the first milestone. 🎊

2021-08-13 08:37 UTC, merged