add new logo for Equalizer token
LedgerHQ/ledger-live-common pull request #1316
Opened 2021-07-20 11:46 UTC by ionutiorgulescu

## Context (issues, jira)

Request (926447)

## Description / Usage

Add a new logo of Equalizer token.

## Expectations

- [ ] **Test coverage: The changes of this PR are covered by test.** Unit test were added with mocks when depending on a backend/device.
- [x] **No impact: The changes of this PR have ZERO impact on the userland.** Meaning, we can use these changes without modifying LLD/LLM at all. It will be a "noop" and the maintainers will be able to bump it without changing anything.

2021-07-20 12:20 UTC, LFBarreto requested changes
hello! :wave: 
thanks for the contribution! in order to keep integration of icons homogeneous through our app we don't allow for use of gradients in icons and usually use a flat design icon.
Also prefer merging all the paths together as we will parse the svg file in order to export components for our mobile and desktop app from it, replacing the `fill` attribute everywhere we find it by the associated color.
Here are a list of supported svg tags you can use to structure your icon: 
- path
- rect
- circle
- polygon
- line
- polyline
- ellipse
- g

Take a look at the other icons we have in the repository in order to see what the format needs to be :+1: 
thanks and don't hesitate to ask for extra info if needed

2021-07-21 13:25 UTC, ionutiorgulescu commented
> hello! 👋
> thanks for the contribution! in order to keep integration of icons homogeneous through our app we don't allow for use of gradients in icons and usually use a flat design icon.
> Also prefer merging all the paths together as we will parse the svg file in order to export components for our mobile and desktop app from it, replacing the `fill` attribute everywhere we find it by the associated color.
> Here are a list of supported svg tags you can use to structure your icon:
> 
> * path
> * rect
> * circle
> * polygon
> * line
> * polyline
> * ellipse
> * g
> 
> Take a look at the other icons we have in the repository in order to see what the format needs to be 👍
> thanks and don't hesitate to ask for extra info if needed

Hi @LFBarreto  thanks for your help, I've pushed a new version of the logo.

2021-07-21 13:35 UTC, LFBarreto approved these changes
:+1:

2021-07-21 14:09 UTC, valpinkman approved these changes

2021-07-21 14:10 UTC, merged