LL-7233 - SWAP - Fix the sort algorithm from usePickDefaultAccount hook
LedgerHQ/ledger-live-common pull request #1433
Opened 2021-10-04 12:56 UTC by jgiamporcaro-ledger

## Context (issues, jira)

[LL-7233]

Use bignumber methods to compare two bignumbers.

## Description / Usage

## Expectations

- [x] **Test coverage: The changes of this PR are covered by test.** Unit test were added with mocks when depending on a backend/device.
- [x] **No impact: The changes of this PR have ZERO impact on the userland.** Meaning, we can use these changes without modifying LLD/LLM at all. It will be a "noop" and the maintainers will be able to bump it without changing anything.

2021-10-05 07:50 UTC, LFBarreto requested changes

2021-10-05 07:50 UTC, LFBarreto commented on src/exchange/swap/hooks/usePickDefaultAccount.ts
>  export const usePickDefaultAccount = (
the reeduce logic seems a bit overcomplicated to me if you're just trying to filter and sort the accounts :shrug: 

```js
const highestbalanceAccount = accounts.filter(acc => acc.balance.gt(0))
                               .sort((a,b) => a.balance.gt(b.balance)))
                               .find(Boolean);
```

should do the trick in that case

2021-10-07 13:42 UTC, LFBarreto approved these changes
LGTM :sweat_smile:

2021-10-08 08:17 UTC, valpinkman approved these changes

2021-10-08 09:33 UTC, gre approved these changes

2021-10-08 09:33 UTC, merged