Add logos for Abachi tokens - ABI, sABI and gABI
LedgerHQ/ledger-live-common pull request #1838
Opened 2022-03-29 11:37 UTC by 0xigor

## Context (issues, jira)

Adding logos for Abachi tokens to ledger

## Description / Usage

Add logos for Abachi tokens - sABI, ABI and gABI to ledger. Support for tokens was added to ledger live desktop already

Contract addresses (polygon)-
ABI   - `0x6d5f5317308C6fE7D6CE16930353a8Dfd92Ba4D7`
sABI - `0x925a785a347f4a03529b06C50fa1b9a10808CAb5`
gABI - `0xEd6AAb1615AaC7BC4C108dFd4Fdc9AD0c8304d47`

## Expectations

- [ ] **Test coverage: The changes of this PR are covered by test.** Unit test were added with mocks when depending on a backend/device.
- [x] **No impact: The changes of this PR have ZERO impact on the userland.** Meaning, we can use these changes without modifying LLD/LLM at all. It will be a "noop" and the maintainers will be able to bump it without changing anything.

2022-03-30 09:53 UTC, LFBarreto requested changes

2022-03-30 09:53 UTC, LFBarreto commented on src/data/icons/svg/ABI.svg
> +    <linearGradient id="a" x1="19.68" x2="11.847" y1="3" y2="23.943" gradientUnits="userSpaceOnUse">
linear gradients, defs, masks, clip-path, filters and inline styles arent valid for our svg icons as we parse them to create react and react native components.
try comparing it to other icons in the repository to check for correct format.
only use svg, path, circle, ellipse, rect, polyline, line tags if needed and add fill="black" as props to them as we will inject color stylings during parsing

thx :pray:

2022-04-01 05:12 UTC, 0xigor commented
@LFBarreto , The SVGs have been updated. Please check and let me know if any other changes are needed.

Thanks!

2022-04-15 16:23 UTC, LFBarreto approved these changes

2022-05-18 17:51 UTC, adrienlacombe-ledger commented
@LFBarreto can we move this to the monorepo by any chance? Thank you!

2022-05-20 07:51 UTC, LFBarreto commented
has been migrated towards https://github.com/LedgerHQ/ledger-live/pull/107
sorry for the delay on this :bow:

2022-05-20 07:51 UTC, closed without merging