fix(tests): hydrate after preload with serialized data
LedgerHQ/ledger-live-common pull request #958
Opened 2020-11-20 17:56 UTC by rjarasson-ledger

`hydrate` is always called after a `preload`, but with a JSON serialized version.
Next preload should result in the same payloads (after deserialization of the hydrated version).

If further preload makes an iterative update from hydrated data, it should not alter data (or reuse a cached version).

2020-11-20 17:59 UTC, rjarasson-ledger commented
I did not tested it against all currencies, so it might report undetected behaviours (that would need fix).

2020-11-20 19:03 UTC, gre commented on src/__tests__/test-helpers/bridge.js
> +        const serialized1 = JSON.parse(JSON.stringify(data1));
data1 can be undefined which will make this line crash.

2020-11-23 14:31 UTC, gre requested changes
see comment.

2020-11-23 17:47 UTC, merged

2020-11-23 17:47 UTC, gre commented
thanks Rémi!